language: julia
codecov: true
os:
  - linux
  - osx
julia:
  - 1.5
  - 1
before_script:
 - julia -e 'using Pkg; Pkg.add(PackageSpec(name="Pavito", rev="master"))' # TODO remove when Pavito #master is released.
jobs:
  allow_failures:
    - julia: nightly
  include:
    - stage: "Documentation"
      julia: 1
      os: linux
      script:
        - julia -e 'using Pkg; Pkg.rm("Pavito")' # TODO Pkg seems to get into troubles because of the `before_script`. Remove when Pavito #master is released.
        - julia --project=docs/ -e 'using Pkg; Pkg.instantiate(); Pkg.develop(PackageSpec(path=pwd()))'
        - julia --project=docs/ docs/make.jl
      after_success: skip
