name = "Alpine"
uuid = "07493b3f-dabb-5b16-a503-4139292d7dd4"
repo = "https://github.com/lanl-ansi/Alpine.jl.git"
version = "0.1.15"

[deps]
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MathProgBase = "fdba3010-5040-5b88-9595-932c9decdf73"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"

[compat]
JuMP = "< 0.19"
MathProgBase = ">=0.6.4"
Cbc = ">= 0.4"
Ipopt = ">= 0.4"
GLPKMathProgInterface = ">=0.4.3"
Pavito = "^0.1"
julia = "^1"

[extras]
Cbc = "9961bab8-2fa3-5c5a-9d89-47fab24efd76"
GLPKMathProgInterface = "3c7084bd-78ad-589a-b5bb-dbd673274bea"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
Pavito = "cd433a01-47d1-575d-afb7-6db927ee8d8f"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Cbc", "GLPKMathProgInterface", "Ipopt", "Pavito", "Pkg", "Test"]
