[deps]
Alpine = "07493b3f-dabb-5b16-a503-4139292d7dd4"
BARON = "2e2ca445-9e14-5b13-8677-4410f177f82b"
CPLEX = "a076750e-1247-5638-91d2-ce28b192dca0"
Cbc = "9961bab8-2fa3-5c5a-9d89-47fab24efd76"
Gurobi = "2e9cd046-0924-5485-92f1-d5272153d98b"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Juniper = "2ddba703-00a4-53a7-87a5-e8b9971dde84"
Pavito = "cd433a01-47d1-575d-afb7-6db927ee8d8f"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[compat]
JuMP = "~1.0"
julia = "1"
